name: Run daily Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-daily-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install Specific ChromeDriver Version
      run: |
        # Set a specific ChromeDriver version
        CHROMEDRIVER_VERSION="114.0.5735.90" # Replace this with the desired version
        
        # Download and install ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run StockList scraper
      run: python Scraping/StockList.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - name: Run StockHistory scraper
      run: python Scraping/StockHistory.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
