on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour at the 0th minute

jobs:
  run-hourly-scraper:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: [7.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run hourly scraper
        run: python Scraping/TopMovers.py
        env:
          MONGODB_URI: mongodb://localhost:27017
      
      - name: Verify MongoDB Data
        run: |
          python -c "
          import pymongo
          client = pymongo.MongoClient('mongodb://localhost:27017')
          db = client['Stock_Web']
          collection = db['top_gainers']
          documents = collection.find()
          for doc in documents:
            print(doc)
            "
        

