on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour at the 0th minute

jobs:
  run-hourly-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run hourly scraper
        run: python Scraping/TopMovers.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # Use a GitHub secret to store your MongoDB Atlas URI

      - name: Verify MongoDB Data
        run: |
          python -c "
          import pymongo
          import os
          from dotenv import load_dotenv

          load_dotenv()
          MONGODB_URI = os.getenv('MONGODB_URI')
          client = pymongo.MongoClient(MONGODB_URI)
          db = client['Stock_Web']
          collection = db['top_gainers']
          documents = collection.find()
          for doc in documents:
            print(doc)
            "
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # Ensure the environment variable is set here as well
