name: Run history Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
    
jobs:
  run-history-info-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run StockHistory scraper
      run: python Scraping/StockHistory.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
