name: Run Scraper

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour at the 0th minute
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller selenium

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v2
      with:
        chrome-version: 'latest'

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver


    - name: Run StockList scraper
      run: python Scraping/StockList.py

    - name: Run StockHistory scraper
      run: python Scraping/StockHistory.py
