name: Run Daily Scraper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-daily-scraper:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: [7.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller
  
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run StockList scraper
        run: python Scraping/StockList.py

      - name: Run StockHistory scraper
        run: python Scraping/StockHistory.py
